[Interface]
Address = 192.168.216.2/32
DNS = 8.8.8.8, 8.8.4.4
PrivateKey = 4Fdqff4+1m8nTrOMGk62xTrAYUBNX86RPmQLB1fM238=
Table = off
PostUp = ip route add 192.168.216.0/24 dev wg0 && ip route add 192.168.88.0/24 dev wg0

[Peer]
AllowedIPs = 192.168.216.0/24, 192.168.88.0/24
Endpoint = hkb0ajgtdbx.vpn.mynetname.net:27246
PersistentKeepalive = 15
PublicKey = W8Wqr8wrlQBZpEbFcIVWXWIhtv7yPe1c04Mlvl0qW10=
